version: '2'

services:
    db:
        container_name: kiwi_db
        image: centos/mariadb-103-centos7
        volumes:
            - db_data:/var/lib/mysql/data
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: kiwi-1s-aw3s0m3
            MYSQL_DATABASE: kiwi
            MYSQL_USER: kiwi
            MYSQL_PASSWORD: kiwi
            MYSQL_CHARSET: utf8
            MYSQL_COLLATION: utf8_unicode_ci

    web:
        container_name: kiwi_web
        depends_on:
            - db
        restart: always
        image: kiwitcms/kiwi:latest
        ports:
          # custom port for http
            - 8081:8080
            - 443:8443
        volumes:
            - uploads:/Kiwi/uploads:Z
            # overriding default configurations - see https://kiwitcms.readthedocs.io/en/latest/configuration.html
            - ./local_settings.py:/venv/lib64/python3.6/site-packages/tcms/settings/local_settings.py
        environment:
            KIWI_DB_HOST: db
            KIWI_DB_PORT: 3306
            KIWI_DB_NAME: kiwi
            KIWI_DB_USER: kiwi
            KIWI_DB_PASSWORD: kiwi
            KIWI_DONT_ENFORCE_HTTPS: "true"

volumes:
    db_data:
    uploads:
